nav:
  - 主页: 'index.md'
  - 23年:
    - bruaket mod: '2023/bruaket mod.md'
    - Barrelcraft: '2023/Barrelcraft.md'
    - earth developer: '2023/earth developer.md'

plugins:
  - markdownextradata: {}
    
markdown_extensions:
  - abbr
  - admonition
  - smarty
  - sane_lists
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

theme: 
    name: material
    language: zh

    
site_name: GoodTime日程表